{% set version = "0.1.3" %}

package:
    name: bluesky-darkframes
    version: {{ version }}

source:
    git_url: https://github.com/bluesky/bluesky-darkframes
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python

    run:
        - bluesky
        - event-model >=1.11.0
        - frozendict
        - numpy

test:
    imports:
        - bluesky_darkframes

about:
    home: https://github.com/bluesky/bluesky-darkframes
    license: BSD
